version: '3'

services:
  flask:
    build: 
      context: ./flask
    volumes: 
      - .:/app
    environment:
      - FLASK_APP=/app/flask/main.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    ##command: uwsgi --ini /app/flask/uwsgi.ini
    command: python -m flask run --host=0.0.0.0 --port 8000 --debugger
    ports:
      - "8000:8000"
    depends_on:
      - mysql

  nginx:
    build:
      context: ./nginx
    volumes:
      - .:/app
    ports:
      - "10000:8080"
    depends_on:
      - flask
      
  mysql:
    image: mysql:5.7
    ports:
    - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root